language: python
python:
  - 3.7

install:
  - pip install -r tools/requirements.txt

script:
  - npx yaspeller -c .yaspellerrc.json .
  - npx eclint check .
  - npx eyo --only-safe --lint "**/*.md"
  - cd tools && bash check_readme.sh